#### Language Code:ES
## Language Version:20250130
## Maximum byte per keyword is 250 Bytes.
## Escape characters are not supported except newline '\n'

label_language:Español
label_command_checksum:Checksum de comandos
label_advanced_ok:OK avanzado
label_tx_delay:TX delay
label_tx_prefetch:TX prefetch
label_emulated_m600:M600 emulado
label_emulated_m109_m190:M109 / M190 emulado
label_event_led:LED de evento
label_file_comment_parsing:Analizar comentarios
label_rotated_ui:Rotar
label_ack_notification:Estilo de notificación ACK
label_files_sort_by:Ordenar archivos por
label_files_list_mode:Vista de lista
label_filename_extension:Ver extensión archivo
label_fan_speed_percentage:Ventilador en porcentaje
label_persistent_info:Infor. de estado persistente
label_terminal_ack:Mostrar ACK en terminal
label_serial_always_on:Com. serie siempre encendida
label_marlin_fullscreen:Marlin a pantalla completa
label_marlin_show_title:Modo Marlin en título
label_marlin_type:Tipo modo Marlin
label_move_speed:Velocidad mov.(X Y Z)
label_auto_load_leveling:Carga autom. de nivelación
label_probing_z_offset:Sondear desvío en Z
label_z_steppers_alignment:Alinear autom. motores Z
label_ps_auto_shutdown:Apagado automático
label_fil_runout:Sensor de filamento
label_pl_recovery:Recuperar corte de corriente
label_pl_recovery_home:Origen tras recuperar corriente
label_btt_mini_ups:BTT UPS Support
label_touch_sound:Sonido al tocar
label_toast_sound:Notif. emergentes
label_alert_sound:Alertas y ventanas
label_heater_sound:Notif. calentador
label_lcd_brightness:Brillo
label_lcd_idle_brightness:Brillo en reposo
label_lcd_idle_time:Tiempo de reposo
label_lcd_lock_on_idle:Bloquear LCD en inactividad
label_led_always_on:LED siempre encendido
label_knob_led_color:LED de perilla rotatoria
label_knob_led_idle:LED de perilla rotatoria en reposo
label_start_gcode_enabled:Añadir GCode pre-impresión
label_end_gcode_enabled:Añadir GCode post-impresión
label_cancel_gcode_enabled:Cancelar GCode
label_steps_setting:Pasos por mm
label_filament_setting:Diámetro filamento
label_maxacceleration:Aceleración máxima
label_maxfeedrate:Cadencia máxima
label_acceleration:Aceleración
label_jerk:Jerk
label_junction_deviation:Junction Deviation
label_home_offset:Desvío origen
label_fwretract:Retracción FW
label_fwrecover:Recuperar retracción FW
label_retract_auto:Retracción firmware automática
label_hotend_offset:Offset 2ª boquilla
label_hotend_pid:PID boquilla
label_bed_pid:PID cama
label_stealth_chop:TMC StealthChop
label_input_shaping:Input Shaping
label_delta_configuration:Delta Configuration
label_delta_tower_angle:Tower Angle Trim
label_delta_diagonal_rod:Diagonal Rod Trim
label_delta_endstop:Ajuste finales carrera
label_probe_offset:Desvío de sonda
label_lin_advance:Avance lineal
label_current_setting:Driver Current (mA)
label_hybrid_threshold:TMC HybridThreshold
label_bump_sensitivity:TMC bump sensitivity
label_mbl_offset:Desvío MBL
label_print_acceleration:Aceleración impresión
label_retract_acceleration:Aceleración retracción
label_travel_acceleration:Aceleración de viaje
label_retract_length:Long. retracción
label_retract_swap_length:Long. retracción en cambio
label_retract_feedrate:Veloc. retracción
label_retract_z_lift:Subida Z en retracción
label_recover_length:Longitud extra recuperación
label_swap_recover_length:Longitud extra recuperación en cambio
label_recover_feedrate:Veloc. recuperación
label_swap_recover_feedrate:Veloc. recuperación cambio
label_save:Grabar
label_restore:Restaurar
label_reset:Reset
label_eeprom_save_info:¿Guardar ajustes en EEPROM?
label_eeprom_restore_info:¿Restaurar ajustes de EEPROM?
label_eeprom_reset_info:¿Resetear EEPROM a valores de fábrica?
label_settings_save:Guardar ajustes
label_settings_restore:Restaurar ajustes
label_settings_reset:Valores predeterminados
label_settings_reset_info:¿Restablecer todos los ajustes?
label_settings_reset_done:Restauración de todos los ajustes finalizada.\nPor favor, reinicia el dispositivo.
label_page_up:Retroceder
label_page_down:Avanzar
label_up:Arriba
label_down:Abajo
label_next:Siguiente
label_back:Volver
label_inc:Aumentar
label_dec:Disminur
label_load:Cargar
label_unload:Descargar
label_on:ON
label_off:OFF
label_auto:AUTO
label_smart:SMART
label_slow:Despacio
label_normal:Normal
label_fast:Rápido
label_zero:Cero
label_half:Mitad
label_full:Todo
label_custom:Misc.
label_clear:Limpiar
label_default:Por defecto
label_start:Iniciar
label_stop:Parar
label_pause:Pausar
label_resume:Continuar
label_init:Init
label_disconnect:Desconectar
label_shut_down:Apagar
label_force_shut_down:Forzar Apagado
label_emergencystop:PARADA
label_preheat:Precalentar
label_preheat_both:Ambos
label_cooldown:Enfriar
label_confirm:Confirmar
label_cancel:Cancelar
label_warning:Advertencia
label_continue:Continuar
label_confirmation:¿Está seguro?
label_status:Estado
label_ready:Preparado
label_busy:Procesando, por favor espere...
label_loading:Cargando...
label_unconnected:¡No hay comunicación con impresora!
label_listening:¡TFT en modo escucha!
label_info:Info
label_invalid_value:Valor(es) no válido(s)
label_timeout_reached:¡Tiempo de espera agotado!
label_disconnect_info:¡Ahora puede controlar la impresora desde su ordenador!
label_shutting_down:Apagando...
label_wait_temp_shut_down:Espere a que la temperatura del hotend sea inferior a %d℃
label_power_failed:¿Continuar imprimiendo?
label_process_completed:¡Proceso completado!
label_process_aborted:¡Proceso cancelado!
label_tft_sd:SD TFT
label_tft_sd_inserted:¡Tarjeta insertada!
label_tft_sd_removed:¡Tarjeta extraida!
label_tft_sd_not_detected:¡No se detecta tarjeta SD!
label_tft_sd_read_error:¡Error en la tarjeta SD!
label_tft_usb:USB
label_tft_usb_inserted:¡USB insertado!
label_tft_usb_removed:¡USB extraido!
label_tft_usb_not_detected:¡No se detecta USB!
label_tft_usb_read_error:¡Error en el USB!
label_onboard_sd:SD Placa
label_onboard_usb:USB Placa
label_onboard_sd_read_error:¡Error en la tarjeta media de la placa!
label_filament_runout:¡Filamento agotado!
label_disable_steppers:Desactivar motores
label_xy_unlock:Desbloquear XY
label_start_print:Comenzar impresión:\n%s?
label_stop_print:¿Desea parar la impresión?
label_is_pause:No se puede extruir al imprimir,\n¿Pausar la impresión?
label_m0_pause:Pausado por comando M0
label_test:Probar
label_deploy:Desplegar
label_stow:Plegar
label_repeat:Repetir
label_hs_on:HS: On
label_hs_off:HS: Off
label_nozzle:Boquilla
label_bed:Cama
label_chamber:Cámara
label_fan:Ventilador
label_bltouch:BLTouch
label_touchmi:TouchMi
label_1_degree:1℃
label_5_degree:5℃
label_10_degree:10℃
label_001_mm:0.01mm
label_01_mm:0.1mm
label_1_mm:1mm
label_5_mm:5mm
label_10_mm:10mm
label_100_mm:100mm
label_200_mm:200mm
label_1_percent:1%
label_5_percent:5%
label_10_percent:10%
label_percent_value:%d%%
label_5_seconds:5 Sec.
label_10_seconds:10 Sec.
label_30_seconds:30 Sec.
label_60_seconds:1 Min.
label_120_seconds:2 Min.
label_300_seconds:5 Min.
label_white:Blanco
label_black:Negro
label_blue:Azul
label_red:Rojo
label_green:Verde
label_cyan:Cyan
label_yellow:Amarillo
label_brown:Marrón
label_gray:Gris
label_orange:Naranja
label_indigo:Indigo
label_violet:Violeta
label_magenta:Magenta
label_purple:Morado
label_lime:Lima
label_darkblue:Azul oscuro
label_darkgreen:Verde oscuro
label_darkgray:Gris oscuro
label_heat:Calentar
label_move:Mover
label_home:Origen
label_print:Imprimir
label_extrude:Extruir
label_settings:Configurar
label_screen_settings:Pantalla
label_ui_settings:Interfaz
label_sound:Sonido
label_marlin_mode_settings:MarlinMode
label_machine_settings:Máquina
label_parameter_settings:Parámetro
label_feature_settings:Añadidos
label_connection_settings:Conexión
label_serial_ports:Com. serie
label_baudrate:Baudios
label_eeprom_settings:EEPROM
label_rgb_settings:Color LED
label_rgb_off:Apagar LED
label_terminal:Terminal
label_leveling:Nivelar
label_point_1:Punto 1
label_point_2:Punto 2
label_point_3:Punto 3
label_point_4:Punto 4
label_point_5:Punto 5
label_bed_leveling:Niv. cama
label_bl_complete:Nivelación completada
label_bl_smart_fill:Los puntos faltantes han sido rellenados inteligentemente.\n\nNota: Recuerda guardar.
label_bl_enable:BL: activar
label_bl_disable:BL: desactivar
label_abl:ABL
label_bbl:BBL
label_ubl:UBL
label_mbl:MBL
label_mbl_settings:Nivelación manual
label_abl_settings:Nivelación automática
label_abl_settings_bbl:Nivelación bilineal
label_abl_settings_ubl:Nivelación unificada
label_abl_settings_ubl_save:Guardar en ranura
label_abl_settings_ubl_load:Cargar ranura
label_abl_slot0:Slot 0
label_abl_slot1:Slot 1
label_abl_slot2:Slot 2
label_abl_slot3:Slot 3
label_abl_slot_eeprom:¿Guardar la malla en EEPROM para cargar al reiniciar?
label_abl_z:Difuminar Z
label_level_corner:Esquina L
label_level_corner_info:La distancia del borde se encuentra por debajo del ajuste X/Y de la sonda y algunos de los puntos de medición podrían no ser alcanzables.\n¿Quieres usar una distancia de borde segura?
label_p_offset:Sonda
label_h_offset:Altura
label_distance:Distancia
label_shim:Calzo
label_load_unload:Cargar/Descargar
label_load_unload_short:(Des)carga
label_touchscreen_adjust:Calibrar
label_more:Más
label_screen_info:Info
label_bg_color:Color de fondo
label_font_color:Color de fuente
label_percentage:Porcentaje
label_percentage_speed:Velocidad
label_percentage_flow:Flujo
label_babystep:MicroAjuste
label_x_inc:+X
label_y_inc:+Y
label_z_inc:+Z
label_x_dec:-X
label_y_dec:-Y
label_z_dec:-Z
label_x:X
label_y:Y
label_z:Z
label_adjust_title:Calibrar la pantalla táctil
label_adjust_info:Por favor, haga clic en el punto rojo
label_adjust_ok:Ajuste correcto
label_adjust_failed:Ajuste fallido, por favor intentelo de nuevo
label_unifiedmove:Mover
label_unifiedheat:Temp.
label_touch_to_exit:Toca cualquier lugar para salir
label_mainmenu:Menu
label_tuning:Ajuste
label_mpc:MPC
label_mpc_title:Autoajuste MPC
label_mpc_method:Método:
label_pid:PID
label_pid_title:Autoajuste PID
label_tune_start_info:El autoajuste puede tomar un tiempo en finalizar.\n¿Continuar?
label_tune_extruder:Pasos
label_tune_ext_extrude_100:Ext. 100mm
label_tune_ext_temp:Ajuste extrusor | Calentar
label_tune_ext_mark120mm:Marca 120 mm en tu filamento.\nPulsa '%s' cuando estés listo.\nMide la longitud restante después de extruir.
label_tune_ext_adj_esteps:Ajustar E-Steps
label_tune_ext_esteps_saved:Nuevos E-steps aplicados.\nNo olvides guardar en EEPROM.\nNuevo valor: %0.2f
label_tune_ext_measured:Longitud restante:
label_tune_ext_old_estep:Pasos anteriores:%0.2f
label_tune_ext_new_estep:Pasos nuevos:%0.2f
label_notifications:Notificaciones
label_mesh_editor:Editor
label_mesh_tuner:Ajustar malla
label_case_light:Luz interior
label_load_started:Cargando filamento.\nPor favor, espera a que el proceso finalice.
label_unload_started:Descargando filamento.\nPor favor, espera a que el proceso finalice.
label_heaters_on:Algún calentador sigue encendido.\n¿Quieres apagarlos?
label_print_finished:   Impresión\n   finalizada
label_main_screen:Inicio
label_previous_print_data:Resumen
label_print_time:Tiempo imp.: %02u:%02u:%02u
label_filament_length:\nLongitud filamento: %1.2fm
label_filament_weight:\nPeso filamento: %1.2fg
label_filament_cost:\nCoste filamento: %1.2f
label_no_filament_stats:\nDatos de filamento no disponibles.
label_click_for_more:Toca para más info
label_ext_templow:Temperatura de boquilla por debajo del mínimo (%d℃).
label_heat_hotend:¿Calentar boquilla a %d℃?
label_desired_templow:La temperatura de boquilla se encuentra por debajo de la temperatura deseada (%d℃).
label_wait_heat_up:Espere a que caliente.
label_z_align:Alinear Z
label_macros:Macros
label_mesh_valid:Validar
label_connect_probe:Conecte la sonda antes de iniciar. Desconéctela al finalizar.
label_disconnect_probe:Asegúrese de desconectar la sonda antes de usar esta función.
label_calibration:Calibrar
